# Schema for the configuration files of the html title module.

html_title.settings:
  type: config_object
  label: 'Content types'
  mapping:
    types:
      type: config_object
      label: 'HTML tags that should be allowed in node title'
